08/05/2018 14:51:09 ERROR [main] Tools:mmserver: 
08/05/2018 14:51:09 ERROR [main] Tools:mmserver: java.lang.NullPointerException
08/05/2018 14:51:09 ERROR [main] actionlog: Error in start ActionLogDbUtils
08/05/2018 14:51:09 ERROR [main] actionlog: java.lang.NullPointerException
08/05/2018 14:52:27 ERROR [main] TCPGOSSIP: failed connecting to clients2.google.com/127.0.0.1:6611: java.lang.Exception: Could not connect to clients2.google.com/127.0.0.1:6611
08/05/2018 14:52:41 ERROR [pool-1-thread-1] ACTIVECARD:type=ProcessManager: DbProcessorAbstract: Tue May 08 14:52:41 CAT 2018
ERROR getRecords: select * from (select * from sm.staff where status = 1 and channel_type_id = 14 and staff_code in ('IT_TEST','MV_PTUD_LINHNBV') order by type) where mod(sub_profile_id, 1) = 0
java.sql.SQLSyntaxErrorException: ORA-00904: "SUB_PROFILE_ID": invalid identifier

08/05/2018 14:52:42 ERROR [pool-1-thread-1] ACTIVECARD:type=ProcessManager: DbProcessorAbstract: Tue May 08 14:52:42 CAT 2018
ERROR getRecords: select * from (select * from sm.staff where status = 1 and channel_type_id = 14 and staff_code in ('IT_TEST','MV_PTUD_LINHNBV') order by type) where mod(sub_profile_id, 1) = 0
java.sql.SQLSyntaxErrorException: ORA-00904: "SUB_PROFILE_ID": invalid identifier

08/05/2018 14:52:43 ERROR [pool-1-thread-1] ACTIVECARD:type=ProcessManager: DbProcessorAbstract: Tue May 08 14:52:43 CAT 2018
ERROR getRecords: select * from (select * from sm.staff where status = 1 and channel_type_id = 14 and staff_code in ('IT_TEST','MV_PTUD_LINHNBV') order by type) where mod(sub_profile_id, 1) = 0
java.sql.SQLSyntaxErrorException: ORA-00904: "SUB_PROFILE_ID": invalid identifier

08/05/2018 14:52:44 ERROR [pool-1-thread-1] ACTIVECARD:type=ProcessManager: DbProcessorAbstract: Tue May 08 14:52:44 CAT 2018
ERROR getRecords: select * from (select * from sm.staff where status = 1 and channel_type_id = 14 and staff_code in ('IT_TEST','MV_PTUD_LINHNBV') order by type) where mod(sub_profile_id, 1) = 0
java.sql.SQLSyntaxErrorException: ORA-00904: "SUB_PROFILE_ID": invalid identifier

08/05/2018 14:52:45 ERROR [pool-1-thread-1] ACTIVECARD:type=ProcessManager: DbProcessorAbstract: Tue May 08 14:52:45 CAT 2018
ERROR getRecords: select * from (select * from sm.staff where status = 1 and channel_type_id = 14 and staff_code in ('IT_TEST','MV_PTUD_LINHNBV') order by type) where mod(sub_profile_id, 1) = 0
java.sql.SQLSyntaxErrorException: ORA-00904: "SUB_PROFILE_ID": invalid identifier

08/05/2018 14:52:46 ERROR [pool-1-thread-1] ACTIVECARD:type=ProcessManager: DbProcessorAbstract: Tue May 08 14:52:46 CAT 2018
ERROR getRecords: select * from (select * from sm.staff where status = 1 and channel_type_id = 14 and staff_code in ('IT_TEST','MV_PTUD_LINHNBV') order by type) where mod(sub_profile_id, 1) = 0
java.sql.SQLSyntaxErrorException: ORA-00904: "SUB_PROFILE_ID": invalid identifier

08/05/2018 15:03:43 ERROR [main] Tools:mmserver: 
08/05/2018 15:03:43 ERROR [main] Tools:mmserver: java.lang.NullPointerException
08/05/2018 15:03:43 ERROR [main] actionlog: Error in start ActionLogDbUtils
08/05/2018 15:03:43 ERROR [main] actionlog: java.lang.NullPointerException
08/05/2018 15:03:49 ERROR [main] TCPGOSSIP: failed connecting to clients2.google.com/127.0.0.1:6611: java.lang.Exception: Could not connect to clients2.google.com/127.0.0.1:6611
08/05/2018 15:29:25 ERROR [main] Tools:mmserver: 
08/05/2018 15:29:25 ERROR [main] Tools:mmserver: java.lang.NullPointerException
08/05/2018 15:29:25 ERROR [main] actionlog: Error in start ActionLogDbUtils
08/05/2018 15:29:25 ERROR [main] actionlog: java.lang.NullPointerException
08/05/2018 15:29:29 ERROR [main] TCPGOSSIP: failed connecting to clients2.google.com/127.0.0.1:6611: java.lang.Exception: Could not connect to clients2.google.com/127.0.0.1:6611
08/05/2018 15:34:36 ERROR [main] Tools:mmserver: 
08/05/2018 15:34:36 ERROR [main] Tools:mmserver: java.lang.NullPointerException
08/05/2018 15:34:36 ERROR [main] actionlog: Error in start ActionLogDbUtils
08/05/2018 15:34:36 ERROR [main] actionlog: java.lang.NullPointerException
08/05/2018 15:34:41 ERROR [main] TCPGOSSIP: failed connecting to clients2.google.com/127.0.0.1:6611: java.lang.Exception: Could not connect to clients2.google.com/127.0.0.1:6611
08/05/2018 15:35:13 ERROR [main] Tools:mmserver: 
08/05/2018 15:35:13 ERROR [main] Tools:mmserver: java.lang.NullPointerException
08/05/2018 15:35:13 ERROR [main] actionlog: Error in start ActionLogDbUtils
08/05/2018 15:35:13 ERROR [main] actionlog: java.lang.NullPointerException
08/05/2018 15:35:16 ERROR [main] TCPGOSSIP: failed connecting to clients2.google.com/127.0.0.1:6611: java.lang.Exception: Could not connect to clients2.google.com/127.0.0.1:6611
08/05/2018 15:36:21 ERROR [main] Tools:mmserver: 
08/05/2018 15:36:21 ERROR [main] Tools:mmserver: java.lang.NullPointerException
08/05/2018 15:36:21 ERROR [main] actionlog: Error in start ActionLogDbUtils
08/05/2018 15:36:21 ERROR [main] actionlog: java.lang.NullPointerException
08/05/2018 15:36:25 ERROR [main] TCPGOSSIP: failed connecting to clients2.google.com/127.0.0.1:6611: java.lang.Exception: Could not connect to clients2.google.com/127.0.0.1:6611
08/05/2018 15:39:10 ERROR [main] Tools:mmserver: 
08/05/2018 15:39:10 ERROR [main] Tools:mmserver: java.lang.NullPointerException
08/05/2018 15:39:10 ERROR [main] actionlog: Error in start ActionLogDbUtils
08/05/2018 15:39:10 ERROR [main] actionlog: java.lang.NullPointerException
08/05/2018 15:39:13 ERROR [main] TCPGOSSIP: failed connecting to clients2.google.com/127.0.0.1:6611: java.lang.Exception: Could not connect to clients2.google.com/127.0.0.1:6611
08/05/2018 15:49:34 ERROR [main] Tools:mmserver: 
08/05/2018 15:49:34 ERROR [main] Tools:mmserver: java.lang.NullPointerException
08/05/2018 15:49:34 ERROR [main] actionlog: Error in start ActionLogDbUtils
08/05/2018 15:49:34 ERROR [main] actionlog: java.lang.NullPointerException
08/05/2018 15:49:38 ERROR [main] TCPGOSSIP: failed connecting to clients2.google.com/127.0.0.1:6611: java.lang.Exception: Could not connect to clients2.google.com/127.0.0.1:6611
08/05/2018 15:51:12 ERROR [main] Tools:mmserver: 
08/05/2018 15:51:12 ERROR [main] Tools:mmserver: java.lang.NullPointerException
08/05/2018 15:51:12 ERROR [main] actionlog: Error in start ActionLogDbUtils
08/05/2018 15:51:12 ERROR [main] actionlog: java.lang.NullPointerException
08/05/2018 15:51:15 ERROR [main] TCPGOSSIP: failed connecting to clients2.google.com/127.0.0.1:6611: java.lang.Exception: Could not connect to clients2.google.com/127.0.0.1:6611
08/05/2018 15:51:55 ERROR [main] Tools:mmserver: 
08/05/2018 15:51:55 ERROR [main] Tools:mmserver: java.lang.NullPointerException
08/05/2018 15:51:55 ERROR [main] actionlog: Error in start ActionLogDbUtils
08/05/2018 15:51:55 ERROR [main] actionlog: java.lang.NullPointerException
08/05/2018 15:51:58 ERROR [main] TCPGOSSIP: failed connecting to clients2.google.com/127.0.0.1:6611: java.lang.Exception: Could not connect to clients2.google.com/127.0.0.1:6611
08/05/2018 15:53:25 ERROR [SALE_DEBIT_BLOCK_Node1.0] 0: ERROR getBranchId IT_TEST
08/05/2018 15:53:25 ERROR [SALE_DEBIT_BLOCK_Node1.0] 0: Error: java.lang.ArrayIndexOutOfBoundsException: 2
	at com.viettel.paybonus.database.DbSaleDebit.getBranchId(DbSaleDebit.java:275)
	at com.viettel.paybonus.process.SaleDebitBlock.processListRecord(SaleDebitBlock.java:89)
	at com.viettel.threadfw.process.ProcessRecordAbstract.process(ProcessRecordAbstract.java:198)
	at com.viettel.mmserver.base.ProcessThread.run(ProcessThread.java:125)
	at java.lang.Thread.run(Thread.java:662)
 Time: 13
08/05/2018 15:54:55 ERROR [main] Tools:mmserver: 
08/05/2018 15:54:55 ERROR [main] Tools:mmserver: java.lang.NullPointerException
08/05/2018 15:54:55 ERROR [main] actionlog: Error in start ActionLogDbUtils
08/05/2018 15:54:55 ERROR [main] actionlog: java.lang.NullPointerException
08/05/2018 15:54:59 ERROR [main] TCPGOSSIP: failed connecting to clients2.google.com/127.0.0.1:6611: java.lang.Exception: Could not connect to clients2.google.com/127.0.0.1:6611
08/05/2018 15:56:29 ERROR [SALE_DEBIT_BLOCK_Node1.0] 0: DbSaleDebit: Tue May 08 15:56:29 CAT 2018
ERROR updateStaff: update sm.staff set limit_over_status = 1, limit_over_last_time = sysdate where staff_id = ?
 staffCode IT_TEST result 0java.sql.SQLSyntaxErrorException: ORA-01031: insufficient privileges

08/05/2018 15:56:29 ERROR [SALE_DEBIT_BLOCK_Node1.0] 0: Error: java.sql.SQLSyntaxErrorException: ORA-01031: insufficient privileges

	at oracle.jdbc.driver.SQLStateMapping.newSQLException(SQLStateMapping.java:221)
	at oracle.jdbc.driver.DatabaseError.newSQLException(DatabaseError.java:137)
	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:257)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:468)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:418)
	at oracle.jdbc.driver.T4C8Oall.receive(T4C8Oall.java:1089)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:216)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:1250)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1516)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3889)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:4033)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:4008)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:147)
	at com.viettel.paybonus.database.DbSaleDebit.updateStaff(DbSaleDebit.java:164)
	at com.viettel.paybonus.process.SaleDebitBlock.processListRecord(SaleDebitBlock.java:114)
	at com.viettel.threadfw.process.ProcessRecordAbstract.process(ProcessRecordAbstract.java:198)
	at com.viettel.mmserver.base.ProcessThread.run(ProcessThread.java:125)
	at java.lang.Thread.run(Thread.java:662)
 Time: 48
